version: "3.1"
services:
  ucurtma-container:
    build:
      context: ./
      dockerfile: ./docker/alpine/Dockerfile
    container_name: ucurtma-container
    environment:
      - BROWSERSTACK_USERNAME=0
      - BROWSERSTACK_ACCESS_KEY=0
      - BROWSERSTACK_USE_AUTOMATE=1
      - BROWSERSTACK_DISPLAY_RESOLUTION=1280x1024
      - REMOTE_FRONTEND_URL=http://non-prod.ucurtmaprojesi.com/
      - BASE_URL=http://non-prod.ucurtmaprojesi.com/
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
